name: Check for Bitrise Comment

on:
  issue_comment:
    types: [created]

jobs:
  run_tests:
    name: Trigger Build with comment
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: [ubuntu-latest]

    steps:
      - name: Get the pull request number
        id: pr_number
        env:
          BITRISE_BUILD_TRIGGER_TOKEN: ${{ secrets.BITRISE_BUILD_TRIGGER_TOKEN }}
        run: |
          echo ::set-output name=number::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - name: PR comment
        if: ${{ github.event.issue.pull_request && contains(fromJSON('["ci run tests", "retest", "run tests"]'), github.event.comment.body) }}
        run: |
          curl https://app.bitrise.io/app/84ddba31cf8de1e2/build/start.json -L --data '{
            "hook_info":{
              "type":"bitrise",
              "build_trigger_token":"$BITRISE_BUILD_TRIGGER_TOKEN"
            },
            "build_params":{
              "branch": "${{ github.head_ref }}",
              "workflow_id": "run-tests",
              "commit_hash": "${{ github.event.pull_request.head.sha }}",
              "pull_request_id": ${{ steps.pr_number.outputs.number }}
            },
            "triggered_by":"curl"
          }'
